map_update_interval: 1.0
maxUrange: 4.8
maxRange: 5.2
sigma: 0.05
kernelSize: 1
lstep: 0.03
astep: 0.03
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 80
srr: 0.03
srt: 0.04
str: 0.03
stt: 0.05
linearUpdate: 0.08
angularUpdate: 0.08
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 40
xmin: -2.6
ymin: -2.6
xmax: 2.6
ymax: 2.6
delta: 0.02
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
